### PR TITLE
Added function to edit start/end time of entry.

### LINKED ISSUE #1: Add option to edit time based on start and end time.
Hi! Thanks for the package. At the moment it's only possible to edit amount oh hours for an entry, am I right? It would be nice to have an option to edit start and end time as well. Do you think it's something you'd like to add? I may push a PR if you want so.

### PR DESCRIPTION
**Pull request by akoppela**
Fixes #1.

### CODE REVIEW

**Comment by xendk** [comment]
Looks good.

The documentation gives the impression that whether to use time span or durations is dictated by the (company) account settings, and it would seem so.

If I inspect `reaper-timeentries` for todays entries, I apparently don't get any start or end times:

```
  (:id . 1077904344)
  (:project_id . 308078)
  (:project . "Internal affairs")
  (:task_id . 271967)
  (:task . "Andet")
  (:is_running)
  (:hours . 1.27)
  (:started_time)
  (:ended_time)
  (:notes . "morgenstatus"))
```

Editing an entry using timespans doesn't work, it stays at the same duration. Can you confirm the reverse case is true for you? I hope it is, then we can rename `reaper-edit-entry-time` to `reaper-edit-entry-duration-time` and create a new `reaper-edit-entry-time` which simply calls one or the other depending on whether `start-time` is defined (I assume that Harvest still provides a calculated `hours`, as the display functions rely on it in order to be able to show anything).

I would have liked some validation on the time strings before passing them to Harvest, but I can see I forgot myself in `reaper-edit-entry-time`.

**Comment by akoppela** [comment]
I can confirm that in duration mode I can not edit start/end time and in timespan mode I can not edit duration.

**Comment by akoppela** [comment]
I've added custom variable now and updated the function accordingly.

**Comment by akoppela** [comment]
Validation on the time string is a nice addition. I can look into it.

**Comment by xendk** [comment]
Nice.

Actually, we don't need the custom variable, we can just check if the edited time entry has a start time.

**Comment by akoppela** [comment]
> Actually, we don't need the custom variable, we can just check if the edited time entry has a start time.

Is that documented behavior? If not then it's not a reliable solution because `stated_in` is a property of time entry object.

**Comment by xendk** [comment]
> Is that documented behavior?

Somewhat:

> started_time: Time the time entry was started (if tracking by start/end times).

> If not then it's not a reliable solution because stated_in is a property of time entry object.

We've already established that editing an entry that doesn't have a `started_time` simply doesn't work, so I'd call it reliable enough.

**Comment by akoppela** [comment]
Indeed there is a way to know if a Harvest expects duration based time tracking or not.

> Create a time entry via duration⚭
> Creates a new time entry object. Returns a time entry object and a `201 Created` response code if the call succeeded.
> You should only use this method to create time entries when your account is configured to **track time via duration**. You can verify this by visiting the **Settings** page in your Harvest account or by checking if `wants_timestamp_timers` is false in the [Company API](https://help.getharvest.com/api-v2/company-api/company/company/).

I checked and i'm able to request company settings with my API key. Could you please verify that it works for you as well?

**Comment by xendk** [comment]
It does, but the documentation also clearly states that `started_time` is only set if the entry is a start/end time entry, so I really don't see the need for another API call.

**Comment by akoppela** [comment]
I see. I agree here. The documentation also says that `timer_started_at` is available only when time is tracked based on duration. Do you think it's nicer to use `timer_started_at` instead of `started_time`?

**Comment by xendk** [comment]
I prefer `started_time` as we're actually using that value. That got a nice feel to it.

**Comment by akoppela** [comment]
Ok. Make sense.

**Comment by xendk** [comment]
Does this still work for you?

I guess `reaper--list-format` should be adjusted in duration mode too.

**Pull request closed without merging**
